### ISSUE TITLE
Plex crashes when opening the channel on android

### ISSUE THREAD

**Issue by clienthax** [japanesemediamanager/plexplugin#24]
Latest versions of stable releases. 3.5.0.2
Also why is the version number of server still 3.5.0.1 on the github?

```
06-17 11:40:58.370 13999 13999 E AndroidRuntime: FATAL EXCEPTION: main
06-17 11:40:58.370 13999 13999 E AndroidRuntime: Process: com.plexapp.android, PID: 13999
06-17 11:40:58.370 13999 13999 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Invalid index 4, size is 4
06-17 11:40:58.370 13999 13999 E AndroidRuntime: 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
06-17 11:40:58.370 13999 13999 E AndroidRuntime: 	at java.util.ArrayList.set(ArrayList.java:481)
06-17 11:40:58.370 13999 13999 E AndroidRuntime: 	at com.plexapp.plex.adapters.c.a.d.a(SourceFile:75)
06-17 11:40:58.370 13999 13999 E AndroidRuntime: 	at com.plexapp.plex.adapters.c.a.g(SourceFile:84)
06-17 11:40:58.370 13999 13999 E AndroidRuntime: 	at com.plexapp.plex.adapters.c.c.a(SourceFile:90)
06-17 11:40:58.370 13999 13999 E AndroidRuntime: 	at com.plexapp.plex.adapters.c.c.onPostExecute(SourceFile:52)
06-17 11:40:58.370 13999 13999 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:651)
06-17 11:40:58.370 13999 13999 E AndroidRuntime: 	at android.os.AsyncTask.access$500(AsyncTask.java:180)
06-17 11:40:58.370 13999 13999 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
06-17 11:40:58.370 13999 13999 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-17 11:40:58.370 13999 13999 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-17 11:40:58.370 13999 13999 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5490)
06-17 11:40:58.370 13999 13999 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-17 11:40:58.370 13999 13999 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-17 11:40:58.370 13999 13999 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by maxpiva** [comment]
Already fixed on the next version of JMMServer

in the midtime:

In **MyAnime.bundle/code/'__init.py'**

Change

`return req.content.replace('</MediaContainer>','<Directory prompt="Search" thumb="'+R(ICON_SEARCH)+'" art="'+R(ICON_SEARCH)+'" key="/video/jmm/search" title="Search" search="1"/><Directory title="Preferences" thumb="'+R(ICON_PREFS)+'" art="'+R(ICON_PREFS)+'" key="/:/plugins/com.plexapp.plugins.myanime/prefs" settings="1"/></MediaContainer>')`

To

`return req.content`

Do not mess with the spaces.
That will fix android, temporary

**Comment by clienthax** [comment]
Yep, loads up now, cheers
